name=ESPOS
version=1.0.1
author=Peter Hakkel Jr.
maintainer=Peter Hakkel Jr.
sentence=Unified ESP8266/ESP32 core helper library.
paragraph=ESP8266/ESP32 framework with captive portal, AP/STA/WiFi repeater, WiFi setup, file manager with .tar support, task manager, and LED driver.
category=Other
url=https://esp8266.org
architectures=esp8266,esp32
